apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: agentic-ai-support
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change-me-in-production"
  DATABASE_URL: "postgresql://postgres:change-me-in-production@postgres:5432/customer_support"
  
  # API Keys (these should be set via external secret management)
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_API_KEY: ""
  
  # JWT Configuration
  JWT_SECRET_KEY: "change-me-in-production-use-long-random-string"
  JWT_ALGORITHM: "HS256"
  
  # External Service Credentials
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AZURE_CLIENT_ID: ""
  AZURE_CLIENT_SECRET: ""
  GCP_SERVICE_ACCOUNT_JSON: ""
  
  # Encryption Keys
  ENCRYPTION_KEY: "change-me-in-production-32-char-key"
  
  # Redis Password (if using auth)
  REDIS_PASSWORD: ""
  
  # Monitoring Credentials
  PROMETHEUS_USERNAME: ""
  PROMETHEUS_PASSWORD: ""
