version: '3.8'

services:
  # Main application
  agentic-ai-customer-support:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=customer_support
      - DB_USER=admin
      - DB_PASSWORD=password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - VECTOR_DB_HOST=qdrant
      - VECTOR_DB_PORT=6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MCP_DATABASE_HOST=mcp-database
      - MCP_DATABASE_PORT=8001
      - MCP_KAFKA_HOST=mcp-kafka
      - MCP_KAFKA_PORT=8002
      - MCP_AWS_HOST=mcp-aws
      - MCP_AWS_PORT=8003
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      qdrant:
        condition: service_started
      redis:
        condition: service_started
      mcp-database:
        condition: service_started
      mcp-kafka:
        condition: service_started
      mcp-aws:
        condition: service_started
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # MCP Database Server
  mcp-database:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8001:8001"
    environment:
      - MCP_SERVER_TYPE=database
      - MCP_SERVER_PORT=8001
      - DATABASE_URL=postgresql://admin:password@postgres:5432/customer_support
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    command: ["python", "-m", "mcp.database_mcp_server"]
    restart: unless-stopped

  # MCP Kafka Server
  mcp-kafka:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8002:8002"
    environment:
      - MCP_SERVER_TYPE=kafka
      - MCP_SERVER_PORT=8002
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    command: ["python", "-m", "mcp.kafka_mcp_server"]
    restart: unless-stopped

  # MCP AWS Server
  mcp-aws:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8003:8003"
    environment:
      - MCP_SERVER_TYPE=aws
      - MCP_SERVER_PORT=8003
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    command: ["python", "-m", "mcp.aws_mcp_server"]
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: customer_support
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  kafka-init:
    image: bitnami/kafka:3.6
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "
      sleep 10 &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic customer-queries &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic agent-events
      "
    restart: "no"

volumes:
  pgdata:
  redisdata: