apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: agentic-ai-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-aws
  labels:
    app: postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: agentic-ai-storage
  awsElasticBlockStore:
    volumeID: vol-0123456789abcdef0  # Replace with actual EBS volume ID
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-aws
  labels:
    app: kafka
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: agentic-ai-storage
  awsElasticBlockStore:
    volumeID: vol-0123456789abcdef1  # Replace with actual EBS volume ID
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-pv-aws
  labels:
    app: qdrant
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: agentic-ai-storage
  awsElasticBlockStore:
    volumeID: vol-0123456789abcdef2  # Replace with actual EBS volume ID
    fsType: ext4
