apiVersion: v2
name: agentic-ai-customer-support
description: A Helm chart for Agentic AI Customer Support application
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - ai
  - customer-support
  - microservices
  - kafka
  - postgres
  - vector-db

maintainers:
  - name: Agentic AI Team
    email: team@agentic-ai.com

sources:
  - https://github.com/agentic-ai/customer-support

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: "22.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
