apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentic-ai-support

resources:
  - ../../base

patchesStrategicMerge:
  - storageclass-patch.yaml
  - ingress-patch.yaml
  - service-patch.yaml

patches:
  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: add
        path: /metadata/annotations/azure.workload.identity~1use
        value: "true"
      - op: add
        path: /metadata/annotations/azure.workload.identity~1service-account-token-expiration
        value: "3600"
  - target:
      kind: Deployment
      name: kafka
    patch: |-
      - op: add
        path: /metadata/annotations/azure.workload.identity~1use
        value: "true"

configMapGenerator:
  - name: azure-config
    literals:
      - AZURE_REGION=East US 2
      - AZURE_RESOURCE_GROUP=agentic-ai-rg
      - STORAGE_CLASS=managed-premium
      - LOAD_BALANCER_SKU=Standard

secretGenerator:
  - name: azure-secrets
    literals:
      - AZURE_CLIENT_ID=change-me
      - AZURE_CLIENT_SECRET=change-me
      - AZURE_TENANT_ID=change-me
      - AZURE_SUBSCRIPTION_ID=change-me

replicas:
  - name: api-deployment
    count: 3
  - name: postgres
    count: 1
  - name: kafka
    count: 3

images:
  - name: api
    newTag: latest
  - name: postgres
    newTag: 15-alpine
  - name: kafka
    newTag: 7.4.0
