version: '3.8'

services:
  # API Service only (no dependencies for testing)
  api-service:
    build:
      context: ..
      dockerfile: ops/api/Dockerfile.api
    ports:
      - "8090:8000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=customer_support
      - DB_USER=admin
      - DB_PASSWORD=password
      - LOG_LEVEL=INFO
    volumes:
      - ../logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
